### ISSUE TITLE
Cookie dismiss button contrast

### ISSUE THREAD

**Issue by peteryates** [dxw/govuk-blogs#110]
Hi. Not sure if this is the right way/place to report it, but the hover style on the cookie banner on blog pages is black on very dark grey when hovering:

https://user-images.githubusercontent.com/128088/141995025-a912b8eb-660b-4104-bbf9-3d8e4722c067.mp4

**Comment by RobjS** [comment]
Hi Peter, thanks for raising this. I can replicate the issue on production - I've raised a ticket in our internal system to get a fix for this put in place, and we'll update you here once that is deployed.

**Comment by brent-dxw** [comment]
Hi Peter. That has been fixed and is deployed to the live site (it may need a hard refresh to view the updated style). Thanks for raising this.
