### ISSUE TITLE
"All posts" feed doesn't work

### ISSUE THREAD

**Issue by MatMoore** [dxw/govuk-blogs#12]
https://www.blog.gov.uk/ has a link to [see all blog posts](https://www.blog.gov.uk/all-posts/). 

I noticed that this page has an [atom feed](https://www.blog.gov.uk/feed/) but it seems like it doesn't work. The XML has no content in it and the updated date is a year ago.

```xml
<?xml version="1.0" encoding="UTF-8"?><feed
	xmlns="http://www.w3.org/2005/Atom"
	xmlns:thr="http://purl.org/syndication/thread/1.0"
	xml:lang="en-US"
	xml:base="https://www.blog.gov.uk/wp-atom.php"
	>
	<title type="text">GOV.UK blogs</title>
	<subtitle type="text"></subtitle>

	<updated>2018-05-09 13:35:57</updated>

	<link rel="alternate" type="text/html" href="https://www.blog.gov.uk" />
	<id>https://www.blog.gov.uk/feed/</id>
	<link rel="self" type="application/atom+xml" href="https://www.blog.gov.uk/feed/" />
</feed>
```

**Comment by mallorydxw** [comment]
Thanks for letting us know about this!

This is a bug with the theme which is used on **www** .blog.gov.uk, not this theme (which is used on all other subsites of blog.gov.uk). So I'll close this issue now and continue working on the problem on an internal ticket.

The fix at the moment will probably be to remove `<link rel="alternate" ...` from www.blog.gov.uk for the moment. My apologies if you were hoping to subscribe to all feeds.
