### ISSUE TITLE
Please remove Storify handling

### ISSUE THREAD

**Issue by leedxw** [dxw/govuk-blogs#15]
Storify URLs stopped working on May 16, 2018

One side effect of the code for interpreting storify.com URLs in old posts is that it is causing CSP errors to be generated.

Please remove the handling of storify from `wp_oembed_add_provider`, and possibly the storify css.

**Comment by snim2** [comment]
@leedxw Is this still an issue?

**Comment by leedxw** [comment]
It's still being added as an approved embed.

https://github.com/dxw/govuk-blogs/blob/8da7af8c84ed0099c407587ad4f68bcf92e0ffdd/lib/embed.php#L8
