### ISSUE TITLE
Dxw\Result\Result

### ISSUE THREAD

**Issue by patrickGDS** [dxw/govuk-blogs#5]
Hi - I am getting the following errors. Can you please tell me what I have missed installing?

Fatal error: Uncaught Error: Class 'Dxw\Result\Result' not found in /Applications/MAMP/htdocs/wordpress/wp-content/themes/govuk-blogs/lib/icon.php:17 Stack trace: #0 /Applications/MAMP/htdocs/wordpress/wp-content/themes/govuk-blogs/templates/header.php(31): blogIconPath() #1 /Applications/MAMP/htdocs/wordpress/wp-includes/template.php(690): require('/Applications/M...') #2 /Applications/MAMP/htdocs/wordpress/wp-includes/template.php(647): load_template('/Applications/M...', false) #3 /Applications/MAMP/htdocs/wordpress/wp-includes/general-template.php(155): locate_template(Array, true, false) #4 /Applications/MAMP/htdocs/wordpress/wp-content/themes/govuk-blogs/templates/base.php(4): get_template_part('templates/heade...') #5 /Applications/MAMP/htdocs/wordpress/wp-includes/template.php(690): require('/Applications/M...') #6 /Applications/MAMP/htdocs/wordpress/wp-includes/template.php(647): load_template('/Applications/M...', false) #7 /Applications/MAMP/htdocs/wordpress/wp-includes/general-template.php(155): locate_templat in /Applications/MAMP/htdocs/wordpress/wp-content/themes/govuk-blogs/lib/icon.php on line 17

**Comment by tomdxw** [comment]
Looks like we forgot to add the [dxw/result](https://packagist.org/packages/dxw/result) composer package.

Should be fixed by running: `composer require dxw/result`

Let me know if that fixes the bug for you.

**Comment by patrickGDS** [comment]
Solution works. Thank you
